# Generated by Django 2.1.5 on 2019-06-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.PositiveIntegerField()),
                ('code3l', models.CharField(max_length=3, unique=True)),
                ('code2l', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('name_official', models.CharField(blank=True, max_length=128, null=True)),
                ('flag_32', models.CharField(blank=True, max_length=255, null=True)),
                ('flag_128', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('zoom', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code2l', models.CharField(max_length=2)),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_official', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.Country')),
            ],
            options={
                'db_table': 'country_name',
            },
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.Country')),
            ],
            options={
                'db_table': 'country_region',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('is_unep', models.IntegerField()),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.AddField(
            model_name='countryregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='countryregion',
            unique_together={('country', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='countryname',
            unique_together={('code2l', 'language')},
        ),
    ]
