# Generated by Django 2.2.1 on 2020-01-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_scorerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_128',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_32',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_official',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Country'),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='name_official',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='countryname',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='countryregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Country'),
        ),
        migrations.AlterField(
            model_name='countryregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
